// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXN5WidOiAmXgi181jthpPqsf75vTg3XE',
    appId: '1:36844156603:web:6131437737e07eecc81b9e',
    messagingSenderId: '36844156603',
    projectId: 'promolist-de655',
    authDomain: 'promolist-de655.firebaseapp.com',
    storageBucket: 'promolist-de655.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbice6Y2YGE3NfAte1Za7S3OFleZkmTwU',
    appId: '1:36844156603:android:ee310cfaa49d8a47c81b9e',
    messagingSenderId: '36844156603',
    projectId: 'promolist-de655',
    storageBucket: 'promolist-de655.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbKmwzO_DNUksc3o_AwrMyYs2yUGyu9oI',
    appId: '1:36844156603:ios:b8a4da561e631961c81b9e',
    messagingSenderId: '36844156603',
    projectId: 'promolist-de655',
    storageBucket: 'promolist-de655.appspot.com',
    iosBundleId: 'com.example.projetoDispositivosMoveis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbKmwzO_DNUksc3o_AwrMyYs2yUGyu9oI',
    appId: '1:36844156603:ios:fc776924922092a4c81b9e',
    messagingSenderId: '36844156603',
    projectId: 'promolist-de655',
    storageBucket: 'promolist-de655.appspot.com',
    iosBundleId: 'com.example.projetoDispositivosMoveis.RunnerTests',
  );
}
