// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClB5dC3JZHUYYjVQVvvFyaYzKn5FQz4NM',
    appId: '1:983907687099:web:3f4a7911aa10959b2b679e',
    messagingSenderId: '983907687099',
    projectId: 'promolist-flutter-c4b04',
    authDomain: 'promolist-flutter-c4b04.firebaseapp.com',
    storageBucket: 'promolist-flutter-c4b04.appspot.com',
    measurementId: 'G-3NCTJP6C0H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAMJRFjVDQl8AKKe6JHd_w0dFnCmPk9f8',
    appId: '1:983907687099:android:b81bc80a2324fe5c2b679e',
    messagingSenderId: '983907687099',
    projectId: 'promolist-flutter-c4b04',
    storageBucket: 'promolist-flutter-c4b04.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0wnzK65c0Lx7g62w1b5hufj_6nHUk_Lw',
    appId: '1:983907687099:ios:e6ddaea73836c24b2b679e',
    messagingSenderId: '983907687099',
    projectId: 'promolist-flutter-c4b04',
    storageBucket: 'promolist-flutter-c4b04.appspot.com',
    iosBundleId: 'com.example.projetoDispositivosMoveis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0wnzK65c0Lx7g62w1b5hufj_6nHUk_Lw',
    appId: '1:983907687099:ios:276954e64d4ee3782b679e',
    messagingSenderId: '983907687099',
    projectId: 'promolist-flutter-c4b04',
    storageBucket: 'promolist-flutter-c4b04.appspot.com',
    iosBundleId: 'com.example.projetoDispositivosMoveis.RunnerTests',
  );
}
